script: 'true'

language: node_js

node_js:
    - "lts/*"
    - "node"
install:
    - npm install -g codecov
    - npm ci
    - grunt doc

after_success:
    - npm test
    - npm run report-coverage
    - codecov

directories:
    - "node_modules"